<div class="pull-left author-card-img">
            <p class="p-1"><a href="[field:spaceurl /]" title="[field:uname/]" target="_blank"><img border="0" src="[field:face/]" /></a></p>
        </div>
<div class="author-card-box">
            <p class="card-name-p"><a class="card-name" href="[field:spaceurl /]" target="_blank">[field:uname/]</a></p>
            <p class="yijuhua" title="[field:sign/]">[field:sign/]</p>
            <p class="p-btn"><a href="/member/index.php?action=guestbook&uid=[field:userid/]" act="add_author" class="dy-btn">给我留言</a>
                <a href="/member/pm.php?dopost=send&uid=[field:userid/]" target="_blank">发送消息</a>

            </p>
        </div>