<?php
$z[0]=Array("item","",2,71);
$z[0][4]['name']="系统优化";
$z[0][4]['link']="dedesafer.php";
$z[0][4]['rank']="";
$z[0][4]['target']="main";
$z[1]=Array("item","",73,150);
$z[1][4]['name']="模块优化";
$z[1][4]['link']="dedesafer.php?ac=plus";
$z[1][4]['rank']="";
$z[1][4]['target']="main";
$z[2]=Array("item","",152,234);
$z[2][4]['name']="检测鉴定";
$z[2][4]['link']="dedesafer.php?ac=checkserv";
$z[2][4]['rank']="";
$z[2][4]['target']="main";

?>