<?php
$z[0]=Array("arcurl","",114,129);
$z[1]=Array("litpic","",157,172);
$z[2]=Array("arcurl","",268,283);
$z[3]=Array("fulltitle","",301,319);
$z[4]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",457,615);
$z[4][4]['runphp']="yes";
$z[5]=Array("writer","",633,648);
$z[6]=Array("pubdate","",694,745);
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("id","",838,849);
$z[8]=Array("id","",898,909);

?>