<?php
$z[0]=Array("php","\r\n              if(\$cfg_mb_open=='Y') {\r\n              echo '游客';\r\n              }\r\n",266,373);
$z[1]=Array("field","",780,803);
$z[1][4]['name']="id";
$z[2]=Array("php","\r\n              if(preg_match(\"/4/\",\$safe_gdopen)){\r\n              echo '验证码:\r\n              <input type=\"text\" name=\"validate\" size=\"4\" class=\"ipt-txt\" style=\"text-transform:uppercase;\"/>\r\n              <img src= \"'.\$cfg_cmspath.'/include/vdimgck.php\" id=\"validateimg\" style=\"cursor:pointer\" onclick=\"this.src=this.src+\\'?\\'\" title=\"点击我更换图片\" alt=\"点击我更换图片\"  class=\"vdimg\"/>';\r\n              }\r\n              ",1302,1748);
$z[3]=Array("php","\r\n            if(\$cfg_mb_open=='Y') {\r\n            echo '\r\n            <script language=\"javascript\" type=\"text/javascript\">CheckLogin2();</script>\r\n            ';\r\n            }\r\n            ",1861,2074);
$z[4]=Array("global","",2737,2762);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",2902,2928);
$z[5][4]['name']="cfg_phpurl";
$z[6]=Array("field","",2966,2982);
$z[6][4]['name']="id";
$z[7]=Array("global","",3373,3398);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",4322,4350);
$z[8][4]['name']="cfg_soft_lang";
$z[9]=Array("field","",4416,4432);
$z[9][4]['name']="id";
$z[10]=Array("global","",4767,4792);
$z[10][4]['name']="cfg_phpurl";
$z[11]=Array("global","",5002,5027);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("global","",5392,5418);
$z[12][4]['name']="cfg_phpurl";
$z[13]=Array("global","",5952,5977);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("global","",6421,6446);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("global","",6925,6953);
$z[15][4]['name']="cfg_soft_lang";
$z[16]=Array("field","",7017,7033);
$z[16][4]['name']="id";
$z[17]=Array("global","",7489,7514);
$z[17][4]['name']="cfg_phpurl";

?>