<?php
$z[0]=Array("match","<div class=\"neirong-box\" id=\"neirong_box\">[ÄÚÈİ]<div class=\"clearfix pages\">",5,106);
$z[1]=Array("trim","<a(.*)>",111,141);
$z[2]=Array("trim","</a>",143,170);
$z[3]=Array("trim","<tbody(.*)>",172,206);
$z[4]=Array("trim","</tbody>",208,239);
$z[5]=Array("trim","<table(.*)>",241,275);
$z[6]=Array("trim","</table>",277,308);
$z[7]=Array("trim","<tr(.*)>",310,341);
$z[8]=Array("trim","</tr>",343,371);
$z[9]=Array("trim","<td(.*)>",373,404);
$z[10]=Array("trim","</td>",406,434);
$z[11]=Array("function","",439,470);

?>