{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130809/1-130PZRZ0.jpg' text='马云“顶”着他的新发型，亮相母校杭州长寿桥小学50年校庆。马云站在当年的班主任面前，师生开怀大笑。' width='1024' height='638'} /uploads/allimg/130809/1-130PZRZ0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZRZ3.jpg' text='马云表示，关于光头新发型，网上有说是和史玉柱打赌输的，没有那么一回事。有一天在家想理一个看看，理完了觉得挺好，通过这一次理的光头，对自己有了新的认识。' width='450' height='600'} /uploads/allimg/130809/1-130PZRZ3.jpg {/dede:img}
