<?php
$z[0]=Array("arcurl","",39,54);
$z[1]=Array("title","",56,70);
$z[2]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",222,380);
$z[2][4]['runphp']="yes";
$z[3]=Array("writer","",398,413);
$z[4]=Array("pubdate","",460,502);
$z[4][4]['function']="GetDateMK(@me)";
$z[5]=Array("arcurl","",602,617);
$z[6]=Array("id","",666,677);
$z[7]=Array("arcurl","",807,822);
$z[8]=Array("litpic","",834,849);

?>