<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/130809/1-130PZS152.jpg ",93,329);
$z[1][4]['ddimg']="/uploads/allimg/130809/1-130PZS152.jpg";
$z[1][4]['text']="当地时间2012年10月29日，美国华盛顿，飓风“桑迪”来袭，奥巴马取消早上的竞选活动，冒雨返回白宫。";
$z[1][4]['width']="1024";
$z[1][4]['height']="683";

?>