<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("fulltitle","",77,95);
$z[2]=Array("description","",121,141);
$z[3]=Array("arcurl","",189,204);
$z[4]=Array("litpic","",216,231);
$z[5]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",356,514);
$z[5][4]['runphp']="yes";
$z[6]=Array("writer","",532,547);
$z[7]=Array("pubdate","",582,628);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("arcurl","",716,731);
$z[9]=Array("id","",785,796);
$z[10]=Array("id","",881,914);
$z[10][4]['function']="GetTags(@me)";

?>