<div class="toutiao idx-toutiao">
            <h2><a href="[field:arcurl/]">[field:fulltitle/]</a></h2>
            <p>[field:description/]</p>
            <div class="box-img"><a href="[field:arcurl/]"><img src="[field:litpic/]"></a></div>
            <div class="box-other">
                <span class="source-quote"><a href="/member/index.php?uid=[field:mid runphp='yes']global $dsql;$sql='SELECT userid FROM dede_member WHERE mid='.@me;$spaceurl = $dsql->GetOne($sql);@me=$spaceurl['userid'];[/field:mid]" target="_blank">[field:writer/]</a></span>
                <time>[field:pubdate function="GetDateTimeMK(@me)"/]</time>
                <span class="comment-box"><i class="icon-comment"></i><a href="[field:arcurl/]#odby" target="_blank"><script src="/plus/pls.php?aid=[field:id/]" language="javascript"></script></a></span>
                <span class="tags-box">[field:id function=GetTags(@me)/]</span></div></div>