{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130809/1-130PZR532.jpg' text='马云：“我见过聪明的人物有很多，孙正义却是其中最特别的。他神色木讷，说很古怪的英语，但是几乎没有一句多余的话，像金庸笔下的乔峰，有点大智若愚。”图为2012年9月19日，日本东京，软银总裁孙正义出席新闻发布会，宣布最新零售计划及依旧换新补贴。' width='1023' height='655'} /uploads/allimg/130809/1-130PZR532.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZR537.jpg' text='马云与孙正义' width='549' height='341'} /uploads/allimg/130809/1-130PZR537.jpg {/dede:img}
