{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130808/1-130PR11143.jpg' text='从竞选到上任后，奥巴马从未停止与社交媒体的密切联系。这是他2011年4月前往Palo Alto Facebook总部与扎克伯格交流，趁此表达他的政见。' width='1024' height='565'} /uploads/allimg/130808/1-130PR11143.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZQH9.jpg' text='平时习惯休闲着装的扎克伯格，为了显示对奥巴马的尊重，特意上身穿了件西装并系上领带，但下半身仍穿牛仔裤和运动鞋，这成了奥巴马调侃的对象。奥巴马笑称：“我叫巴拉克·奥巴马，是我让马克穿上了西服外套，系上了领带。”' width='550' height='400'} /uploads/allimg/130809/1-130PZQH9.jpg {/dede:img}
