<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("fulltitle","",94,112);
$z[2]=Array("description","",138,158);
$z[3]=Array("arcurl","",206,221);
$z[4]=Array("litpic","",249,264);
$z[5]=Array("writer","",358,373);
$z[6]=Array("pubdate","",404,450);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("arcurl","",538,553);
$z[8]=Array("id","",611,622);
$z[9]=Array("id","",707,740);
$z[9][4]['function']="GetTags(@me)";

?>