<div class="toutiao idx-toutiao">
            <h2><a href="[field:arcurl/]" target="_blank" >[field:fulltitle/]</a></h2>
            <p>[field:description/]</p>
            <div class="box-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"></a></div>
            <div class="box-other">
                <span class="source-quote">[field:writer/]</span>
                <time>[field:pubdate function="GetDateTimeMK(@me)"/]</time>
                <span class="comment-box"><i class="icon-comment"></i><a href="[field:arcurl/]#postform" target="_blank"><script src="/plus/pls.php?aid=[field:id/]" language="javascript"></script></a></span>
                <span class="tags-box">[field:id function=GetTags(@me)/]</span>
            </div>
        </div>