<?php
$z[0]=Array("field","",358,377);
$z[0][4]['name']="title";
$z[1]=Array("global","",378,404);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",525,547);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",595,646);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1275,1310);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1632,1888);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[6]=Array("type","[field:typename /]",1997,2038);
$z[7]=Array("field","",2230,2251);
$z[7][4]['name']="content";
$z[8]=Array("include","",2403,2440);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("include","",2529,2565);
$z[9][4]['filename']="login.htm";

?>