<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'uavLvr3pydw=');
$cfg_Cs[2]=array(0,1,1,'vs3SvcXj1e8=');
$cfg_Cs[3]=array(0,1,1,'uN+2y8zlvOw=');
$cfg_Cs[4]=array(0,1,1,'vvzX1rL6xrc=');
$cfg_Cs[5]=array(0,1,1,'xvPStbnLzso=');
$cfg_Cs[6]=array(0,2,1,'vs3SvdfK0bY=');
$cfg_Cs[7]=array(0,17,1,'warPtc7Sw8c=');
$cfg_Cs[8]=array(7,17,1,'udjT2s7Sw8c=');
$cfg_Cs[9]=array(7,17,1,'vNPI687Sw8c=');
$cfg_Cs[10]=array(7,17,1,'ueO45rywt/7O8Q==');
$cfg_Cs[11]=array(7,17,1,'s6O8+87KzOK94rTw');
?>