{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130809/1-130PZR015.jpg' text='当地时间2012年10月11日，瑞典斯德哥尔摩，瑞典皇家科学院常务秘书彼得·英格伦宣布中国作家莫言获得2012年诺贝尔文学奖。' width='1024' height='681'} /uploads/allimg/130809/1-130PZR015.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZR212.jpg' text=' 当日，2012年诺贝尔文学奖得主莫言携家人及朋友从北京首都国际机场出发，前去瑞典领取诺贝尔文学奖。 ' width='645' height='436'} /uploads/allimg/130809/1-130PZR212.jpg {/dede:img}
