{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130809/1-130PZS325.jpg' text='北京时间11月7日中午12点15分，2012年美国总统选举投票结果出炉：巴拉克·奥巴马率先夺得270张选举人票，成功当选美国第57届总统。这是2011年3月19日，巴西巴西利亚，奥巴马检阅仪仗队。' width='1024' height='683'} /uploads/allimg/130809/1-130PZS325.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZS424.jpg' text='奥巴马宣誓就职第57届美国总统' width='914' height='537'} /uploads/allimg/130809/1-130PZS424.jpg {/dede:img}
