<dl>
                    <dt><a href="[field:arcurl/]">[field:title/]</a></dt>
                    <dd>
                        <p>
                            <span class="source-quote"><a href="/member/index.php?uid=[field:mid runphp='yes']global $dsql;$sql='SELECT userid FROM dede_member WHERE mid='.@me;$spaceurl = $dsql->GetOne($sql);@me=$spaceurl['userid'];[/field:mid]" target="_blank">[field:writer/]</a></span>
                            <time>[field:pubdate function="GetDateMK(@me)"/]</time>
                            <span class="comment-box"><i class="icon-comment"></i><a href="[field:arcurl/]" target="_blank"><script src="/plus/pls.php?aid=[field:id/]" language="javascript"></script></a></span>
                        </p>
                        <div class="box-img"><a href="[field:arcurl/]"><img src="[field:litpic/]"></a></div>
                    </dd>
                </dl>