<div class="clearfix view-box">
                <div class="pull-left img-box">
                    <p><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"/></a></p></div>
                <div class="view-box-ctt">
                    <h4><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></h4>
                    <div class="box-other">
                        <span class="source-quote"><a href="/member/index.php?uid=[field:mid runphp='yes']global $dsql;$sql='SELECT userid FROM dede_member WHERE mid='.@me;$spaceurl = $dsql->GetOne($sql);@me=$spaceurl['userid'];[/field:mid]" target="_blank">[field:writer/]</a></span>
                        <p><time>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</time><span class="comment-box"><i class="icon-comment"></i><a href="/plus/feedback.php?aid=[field:id/]" target="_blank"><script src="/plus/pls.php?aid=[field:id/]" language="javascript"></script></a></span></p>
                    </div>
                </div>
            </div>