{dede:noteinfo notename="¿´µã" channelid="1" macthtype="string"
refurl="http://www.huxiu.com/focus" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.huxiu.com/focus{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="row-fluid-wrap-hx">{/dede:areastart}
    {dede:areaend}<div class="clearfix pages">{/dede:areaend}
{/dede:listrule}
