<?php
$z[0]=Array("arcurl","",112,127);
$z[1]=Array("litpic","",155,170);
$z[2]=Array("arcurl","",266,281);
$z[3]=Array("fulltitle","",299,317);
$z[4]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",455,613);
$z[4][4]['runphp']="yes";
$z[5]=Array("writer","",631,646);
$z[6]=Array("pubdate","",692,743);
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("id","",836,847);
$z[8]=Array("id","",896,907);

?>