<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("litpic","",119,134);
$z[2]=Array("arcurl","",248,263);
$z[3]=Array("fulltitle","",281,299);
$z[4]=Array("writer","",406,421);
$z[5]=Array("pubdate","",460,506);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",548,568);
$z[7]=Array("id","",594,627);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",777,792);
$z[9]=Array("id","",846,857);

?>