{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/130809/1-130PZU020.jpg' text='借助铁杆用户热盼的微信5.0的正式发布，腾讯股价一路飙升，再创历史新高，收于370.8港元，上涨3%，昨日收盘价也达到其2004年上市发行价的100倍。' width='620' height='413'} /uploads/allimg/130809/1-130PZU020.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130809/1-130PZU055.jpg' text='据新京报8月6日报道，截至昨日，腾讯市值已高达5421亿元人民币，而腾讯“掌门人”马化腾也借此登上2013年全球亿万富豪榜第173位，资产达68亿美元，身家在国内互联网领域仅次于百度的CEO李彦宏。' width='700' height='393'} /uploads/allimg/130809/1-130PZU055.jpg {/dede:img}
