<div class="clearfix view-box">
                <div class="pull-left img-box">
                    <p><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"/></a></p></div>
                <div class="view-box-ctt">
                    <h4><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></h4>
                    <div class="box-other">
                        <span class="source-quote">[field:writer/]</span>
                        <p><time>[field:pubdate function="GetDateTimeMK(@me)"/]</time><span class="comment-box"><i class="icon-comment"></i><a href="[field:arcurl/]#odby" target="_blank"><script src="/plus/pls.php?aid=[field:id/]" language="javascript"></script></a></span></p>
                    </div>
                </div>
            </div>