<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("litpic","",118,133);
$z[2]=Array("arcurl","",222,237);
$z[3]=Array("fulltitle","",255,273);
$z[4]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",411,569);
$z[4][4]['runphp']="yes";
$z[5]=Array("writer","",587,602);
$z[6]=Array("pubdate","",645,691);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("id","",810,821);
$z[8]=Array("id","",870,881);
$z[9]=Array("description","",965,985);
$z[10]=Array("id","",1011,1044);
$z[10][4]['function']="GetTags(@me)";

?>