<?php
$z[0]=Array("field","",358,377);
$z[0][4]['name']="title";
$z[1]=Array("global","",378,404);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",453,482);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",530,588);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1165,1190);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",1450,1476);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("include","",1662,1697);
$z[6][4]['filename']="head.htm";
$z[7]=Array("list","\r\n\r\n                <dl>\r\n                <dt><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></dt>\r\n                <dd><time>[field:stime/]</time><span class=\"comment-box\"><i class=\"icon-click\"></i>[field:click/]</span></dd>\r\n                <dd>[field:description/]</dd>\r\n            </dl>                \r\n			",2014,2395);
$z[7][4]['orderby']="sortrank";
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",2539,2568);
$z[8][4]['listsize']="4";
$z[9]=Array("include","",2640,2677);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("include","",2766,2802);
$z[10][4]['filename']="login.htm";

?>